---
  - hosts: database
    become: true
    tasks:
      - name: install mariadb DataBase
        yum:
          name: mariadb-server
          state: present
          update_cache: yes
      - name: Install the Python MySQL Support Libraries
        yum: pkg=MySQL-python state=latest

      - name: start mysql server and enable it on reboot
        service: name=mariadb state=started enabled=true
