---
  - hosts: database
    become: true
    tasks:
      - name: install tools
        yum: name={{item}} state=present update_cache=yes
        with_items:
          - MySQL-python

      - name: install MySQL-Server DataBase
        yum: name=mysql-server state=present update_cache=yes
        notify: restart mysql

      - name: ensure mysql listening on all ports
        lineinfile: dest=/etc/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
        notify: restart mysql

      - name: Install the Python MySQL Support Libraries
        yum: pkg=MySQL-python state=latest

      - name: create demo database
        mysql_db: name=demo state=present

      - name: create demo user
        mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present


    handlers:
      - name: restart mysql
        service: name=mysqld state=restarted
