---
  - hosts: loadbalancer
    become: tue
    tasks:
     - name: verify nginx service
       command: service nginx status

     - name: verify nginx is listening on 80
       wait_for: port=80 timeout=3

  - hosts: webserver
    become: true
    tasks:
     - name: verify apache service
       command: service httpd status

     - name: verify apache is listening on 80
       wait_for: port=80 timeout=3

  - hosts: database
    become: true
    tasks:
     - name: verify mysql service
       command: service mysql status

     - name: verify MySQL is listening on 3306
       wait_for: port=3306 timeout=3
