---
# tasks file for mysql
- name: install tools
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - MySQL-python

- name: Install the MySQL repo
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    state: present
  when: ansible_os_family == "RedHat"

- name: install MySQL-Server DataBase
  yum: name=mysql-server state=present update_cache=yes

- name: copy config file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql

- name: ensure mysql listening on all ports
  lineinfile: dest=/etc/my.cnf regexp=^bind-address
              line="bind-address = {{ ansible_eth0.ipv4.address }}"
  notify: restart mysql

#- name: ensure mysql service is running
  #service: name=mysqld state=restarted enabled=yes

- name: Install the Python MySQL Support Libraries
  yum: pkg=MySQL-python state=latest

- name: create demo database
  mysql_db: name=demo state=present

- name: create demo user
  mysql_user:
    name: demo
    password: demo
    priv: 'demo.*:ALL'
    host: '%'
    state: present
